spring:
  datasource:
      url: jdbc:postgresql://localhost:5434/University
      username: postgres
      password: admin
      driverClassName: org.postgresql.Driver

  flyway:
      enabled: true
      user: postgres
      password: admin
      schemas: public
      url: jdbc:postgresql://localhost:5434/University
